version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: cost-explorer-db
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~